// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  advantages: dynamic(() => import("./Advantages")),
  booking: dynamic(() => import("./Booking")),
  games: dynamic(() => import("./Games")),
  hero: dynamic(() => import("./Hero")),
  rules: dynamic(() => import("./Rules")),
};
