// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  advantages: dynamic(() => import("./Advantages")),
  hero: dynamic(() => import("./Hero")),
};
